name: release-drafter

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Update Release Draft
        uses: release-drafter/release-drafter@v5
        with:
          config-file: .github/release-drafter.yml

...

template: |
  ## Changes

  $CHANGES
