# Makefile for Hugo Website Project

# Variables
HUGO_VERSION := 0.88.1

# Targets
setup:
    ./setup.sh

build:
    hugo

clean:
    make -C /home/el_caiamn/Desktop/Holberton/holbertonschool-validation/module3_task1

test:
    make -C /home/el_caiamn/Desktop/Holberton/holbertonschool-validation/module3_task1

deploy:
    make -C /home/el_caiamn/Desktop/Holberton/holbertonschool-validation/module3_task1

version:
    hugo version

.PHONY: setup build clean test deploy version
