[build]
  base = "/"
  publish = "public/"
  command = "npm run build"  # Suponiendo que utilizas npm para construir
  publish = "out/"  # Ruta donde se encuentran los archivos generados por Next.js
 