name: module3_task1

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Hugo environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git make
          chmod +x ./setup.sh
          ./setup.sh

      - name: Build website
        run: make build
