name: module3_task1

on:
  push:
    branches:
      - main
  pull_request:

  schedule:
    - cron: 0 0 * * *
jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./module3_task1
    steps:
      - uses: actions/checkout@v3
      - name: Set up Hugo environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git make
          chmod +x ./setup.sh
          ./setup.sh
      - name: Build website
        run: make build
          ./setup.sh 
      - name: make-help
        run: |
          make help
      - name: make-build
        run: |
          make build
      - name: make-post
        run: |
          make POST_NAME=who-are-we POST_TITLE="Who are we" post
      - name: make-clean
        run: |
          make clean
          ls
