name: module3_task1

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Hugo environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git make
          chmod +x ./setup.sh
          ./setup.sh

      - name: Build Hugo Site
        run: hugo

      - name: Make Clean
        run: make clean

      - name: Make Build
        run: make build

      - name: Make Test
        run: make test

      - name: Make Deploy
        run: make deploy

      - name: Display Hugo Version
        run: hugo version

