name: module3_task0

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Schedule to run daily at midnight UTC

jobs:
  validate:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate Makefile
        run: cd ./module3_task1/ && make help

      - name: Hugo
        run: |
            cd module3_task1
            ./setup.sh

      - name: build
        run: |
            cd module3_task1
            make build

      - name: test
        run: |
          cd module3_task1
          make test

      - name: run
        run: |
          cd module3_task1
          make run

      - name: clean
        run: |
          cd module3_task1
          make clean

        
