name: Module 3 Task 0

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Schedule to run daily at midnight UTC

jobs:
  validate:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x # Use the desired Go version

      - name: Build and Test
        run: |
          make help
