name: Release Drafter
on:
  push:
    branches:
      - main
      - release/*
      - feature/*
      - hotfix/*
      - fix/*

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Other steps...
      
      - name: Run module3_task4
        uses: ./.github/workflows/module3_task4.yml  # Directly reference the file
